# -*- mode: ruby -*-
# vi: set ft=ruby :

IS_WINDOWS = (RbConfig::CONFIG["host_os"] =~ /mswin|mingw|cygwin/) ? true : false
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise32"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.synced_folder "../", "/home/vagrant/src", :nfs => !IS_WINDOWS
end